name: Backend CI

on:
  push:
    branches: [ main, master ] # Adjust branch names as needed
  pull_request:
    branches: [ main, master ] # Adjust branch names as needed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Match project's Python version

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH # Older uv versions might install to .cargo/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH # Newer uv versions install to .local/bin

    - name: Install Dependencies
      run: |
        # Ensure uv is available
        which uv
        uv --version
        # Install project dependencies using uv
        uv pip sync pyproject.toml
        # Install the project in editable mode
        uv pip install -e . --system # Using --system as it's in a CI container

    - name: Run Pytest
      run: |
        # Add src to PYTHONPATH if necessary, though editable install should handle it
        # export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest tests/
